// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://baapydgspxpteiflnben.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJhYXB5ZGdzcHhwdGVpZmxuYmVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NjQ0NjYsImV4cCI6MjA3NDQ0MDQ2Nn0.N9erraYi0sxAk4i5hyODafTSeEEHKoKyLFC-L4gjBTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});